# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create app on Apple Developer and App Store Connect sites"
  lane :create_app do
​    produce
  end
 
  desc "Create ipa"
  lane :build do
    	enable_automatic_code_signing
    	increment_build_number
    	gym
  end


 desc "Generate development  Certificate and Signin profile"	
 lane :Certificate_Profile_Generate do
      cert(
	development: true,
  	username: "user@email.com"
      )
      sigh(
	force: true,
	username: "user@email.com"
	app_identifier: "App ID"
      )
  end


  desc "Upload an app to TestFlight" 
  lane :beta do
  	sync_code_signing(type: "appstore")    # see code signing guide for more information
  	build_app(scheme: "MyApp")
  	upload_to_testflight(changelog: "Message")
    end


  desc “Create app, Generate Certificate and Providing profile, Create ip and Upload on TestFlight"
  lane :do_everything do
    create_app
    build
    Certificate_Profile_Generate
    beta
  end

end
